### ISSUE TITLE
Handling existing attachments fails

### ISSUE THREAD

**Issue by eddybl** [paulscherrerinstitute/py_elog#10]
If I want to .post an entry with an existing attachment the script will fail.
This example:
`from elog.logbook import Logbook as elog`
`log = elog('http://localhost:8080/demo/')`
`msg, data, attachments = log.read(142)`
`log.post(msg, attachments=attachments)`

will lead to this error message:

> File "**/logbook.py", line 434, in _prepare_attachments
    prepared.append((attribute_name, (filename, file_obj)))
> UnboundLocalError: local variable 'attribute_name' referenced before assignment

This happens because the 'attribute_name' variable will only be defined if the attachment is an file like object or a string which is does not start with self._url, but not in the case if it is an URL

**Comment by eddybl** [comment]
Open further testing I am not sure why it is tried to handle url attachments in this way, since they are not being replaced anyway if one edits a message and just adds new attachments to the query

**Comment by simongregorebner** [comment]
Why things are treated this way I cannot tell, but with the 1.3.3 at least the UnboundLocalError should not happen any more.

**Comment by simongregorebner** [comment]
I guess we can close this one.
