### ISSUE TITLE
Editing entry will remove content from certain attributes

### ISSUE THREAD

**Issue by eddybl** [paulscherrerinstitute/py_elog#11]
If you use the Logbook.post method to edit an existing entry all values in the existing entry will be lost if the corresponding attribute has some whitespace
**Elog Config**
`attributes = Attr1, Attr2, Attr 3, Attr4, Attr 5, Attr 6, Attr 7, Attr8`

**Steps to reproduce**

1. Create Elog Entry using Webfrontend adding text to all 8 attributes
2. Run the below code example
3. All attributes with a whitespace will be empty (Attr 3, 5, 6, 7)

**Code example**
`from elog.logbook import Logbook`
`elog = Logbook('http://localhost:8080/demo2/')`
`elog.post('After editing',msg_id=1)`
**Screenshots showing before / after**
https://ibb.co/KVJY5CJ

**Comment by eddybl** [comment]
#12

**Comment by simongregorebner** [comment]
Thanks @eddybl for figuring this out and submitting the merge request! Its now in.
