### ISSUE TITLE
search functionality

### ISSUE THREAD

**Issue by gorela** [paulscherrerinstitute/py_elog#16]
hi,

is there a way to search, or just read all messages and do offline search?

cheers from mainz,
pepe

**Comment by simongregorebner** [comment]
right now there is no search, no.
I will keep this issue open as a feature request. (feel free to create a pull request if you're faster implementing this ; ) )

**Comment by gorela** [comment]
i implemented a simple search funtion that returns ids. i would like to share it.

**Comment by gorela** [comment]
and i am not allowed to push to a new branch

**Comment by simongregorebner** [comment]
Hey, this is how you can contribute your changes to this repo:
https://guides.github.com/activities/forking/
An other option if the code you created is small, paste it here and I will bing it into the codebase.
