### ISSUE TITLE
Error when posting a message

### ISSUE THREAD

**Issue by matteopanca** [paulscherrerinstitute/py_elog#2]
Hi,
I'm working with Python 3.5.3 on Windows 10.
I tried to post a message using the "logbook.post()" method in a localhost elog (succesfully opened with py_elog). I inserted 2 attributes as **kwargs (i.e. "Category" and "Type" in my case) and it returned the following error:

> c:\anaconda3\lib\site-packages\elog-1.1.0-py3.5.egg\elog\logbook.py in post(self, message, msg_id, reply, attributes, attachments, encoding, **kwargs)
178             # As we create a new message, specify creation time if not already specified in attributes
179             if 'When' not in attributes:
--> 180                 attributes['When'] = int(datetime.now().strftime('%s'))
181
182         if not attributes_to_edit:
ValueError: Invalid format string

I tried with "datetime.datetime.now()" in my ipython session and it's correctly returning the date, but it doesn't recognize the "%s" format string in strftime('%s').

Do you have any hint?

Many thanks,
Matteo

**Comment by matteopanca** [comment]
Additional comment: when I specify the "When" attribute, using the "When" entry in the "attributes" dictionary, the "post" method works fine, but it uses the current date-time for any value I try. For example,
`attributes={'When': 1}`
is accepted and the generated entry has the current date-time in the "Date" column.

**Comment by simongregorebner** [comment]
The required attributes to pass to the post function are determined by the elog configuration.
Can you let me know how your elog config looks like?

**Comment by matteopanca** [comment]
Here we go:

> [ASI]
> Theme = default
> Comment = ASI Project - ToDo List
> Attributes = Category, Type, Status, Subject
> Options Category = Laser Heating, kMC, Micromagnetism
> Options Type = Draft, Comment, Code, Data, Simulation
> Extendable Options = Category, Type
> Required Attributes = Category, Type
> 
> Options Status = Done, Under Process, Not Working
> Cell Style Status Done = background-color:green
> Cell Style Status Not Working = background-color:red
> Cell Style Status Under Process = background-color:yellow
> 
> Page Title = ELOG - $Subject
> Reverse sort = 1
> Quick filter = Date, Category, Type, Status

**Comment by simongregorebner** [comment]
sorry, but can you also please post the exact api call you are using.

**Comment by matteopanca** [comment]
Of course! After having opened the logbook in "logbook", I call:
`logbook.post('Test', attributes={'Category': 'kMC', 'Type': 'Simulation'})`
and I get the error you see in the first comment.

If I call:
`logbook.post('Test', attributes={'Category': 'kMC', 'Type': 'Simulation', 'When': 1})`
the entry is correctly added to the logbook with the current date-time.

**Comment by simongregorebner** [comment]
I somehow not able to reproduce the issue on one of my machines (but all are non windows) =(

If I get your first post correctly, this piece of code does not work in your Python interpreter, right?
```python
from datetime import datetime
datetime.now().strftime('%s')
```

**Comment by matteopanca** [comment]
`datetime.now()` works fine, but with `datetime.now().strftime('%s')` I get the error "Invalid format string" (Python 3.5.3)

If you check here ( https://docs.python.org/3.5/library/datetime.html#strftime-strptime-behavior ), there is no '%s' format string (also for 3.6).

**Comment by simongregorebner** [comment]
Actually we hit this here: https://stackoverflow.com/questions/11743019/convert-python-datetime-to-epoch-with-strftime
I will fix it with the suggested solution...

**Comment by simongregorebner** [comment]
I just tagged a new version 1.3.0 and triggered a build - in a view minutes you should be able to install the new version

**Comment by matteopanca** [comment]
Thanks!
