### ISSUE TITLE
Upload Attachments

### ISSUE THREAD

**Issue by bschuler** [paulscherrerinstitute/py_elog#22]
Hello, 

How can one add an attachment to a new or existing entry?
E.g. if I want to upload an image.

Thanks for the help!

**Comment by simongregorebner** [comment]
have you been already able to figure this out yourself?

**Comment by bschuler** [comment]
No unfortunately not... Any idea?

**Comment by eddybl** [comment]
Did you have a look at the documentation of the `post` method?
https://github.com/paulscherrerinstitute/py_elog/blob/master/elog/logbook.py#L108

It is pretty specific: https://github.com/paulscherrerinstitute/py_elog/blob/master/elog/logbook.py#L120

You actually just have to provide a list of attachments you want to add

**Comment by simongregorebner** [comment]
This should be fixed with the latest changes in the attachment uploads
