### ISSUE TITLE
ELog Server Version dependent code?

### ISSUE THREAD

**Issue by eddybl** [paulscherrerinstitute/py_elog#25]
ELog at some point fixed this bug ( https://elog.psi.ch/elog/download/ChangeLog ):
 - Fixed "?npp=0" crash

This would make this part in the search method obsolete and allow search to return as many elements as it finds:
```
 # Putting n_results = 0 crashes the elog. also in the web-gui.
 n_results = 1 if n_results < 1 else n_results
```

But this can only be done for ELog Server Versions >= 3.1.4
The version is available in the HTTP Response Header, but it is obviously to late at this point, since the information would be required BEFORE the search.

One possible solution would be to make a HTTP request during __init__ to obtain the version number.  Right now the __init__ function only sets attributes, so this might(?) break behavior compared to now.

An alternative would be to add the version number to the object only after the first request by adding some code to the `_validate_response` method. This would not change the behavior in general but might lead to the situation that the very first search behaves differently than the second search.

What do you think?

**Comment by simongregorebner** [comment]
Not sure about how to solve this in a clean way. I guess there is no way around a hello/get version call (something like a hello -what version are you) before issuing the first real request.

**Comment by simongregorebner** [comment]
I just checked a get call against https://elog.psi.ch - there I cannot find elog version information in the response ...
