### ISSUE TITLE
Problem while opening a logbook

### ISSUE THREAD

**Issue by matteopanca** [paulscherrerinstitute/py_elog#3]
Hi,
I'm working with Python 3.5.3 on Windows 10.
I tried to open a localhost elog by using the constructor with detailed arguments described in the Readme:

> logbook = elog.open('localhost', logbook='ASI', port=80, use_ssl=False)

However, the value of the "_url" attribute is

> In[34]: logbook._url
> Out[34]: 'http:///ASI/'

 and so it tells me the url is not valild when trying to perform any operation on the logbook.
Anyway, "logbook = elog.open('http://localhost/ASI')" works perfectly and returns the correct url.

Do you have any hint?

Many thanks,
Matteo

**Comment by simongregorebner** [comment]
So am I right that your logbook is running on 'localhost'?

**Comment by matteopanca** [comment]
Yes, I'm working on the same machine elog is installed on. If I write "http://localhost/ASI" in my web browser I have access to the "ASI" logbook.

**Comment by matteopanca** [comment]
An additional comment. If you try:

`hostname = 'localhost'`
`parsed_url = urllib.parse.urlsplit(hostname)`

then, "parsed_url" contains

> SplitResult(scheme='', netloc='', path='localhost', query='', fragment='')

So, when using 'localhost' (or any non-url string) as the first argument of the "open" method, the "netloc" attribute remains empty and a proper "logbook._url" cannot be generated.

**Comment by simongregorebner** [comment]
until the new package version is out, a workaround for this is to use http://localhost as first argument
