### ISSUE TITLE
Does a package of py_elog exist on PyPI? 

### ISSUE THREAD

**Issue by abulgher** [paulscherrerinstitute/py_elog#31]
I would like to install py_elog from PyPI just using pip and not conda. 

I have developed my own package that rely on your py_elog. I can download the source of py_elog, build the package locally and then have my package running, but if I want to distribute my package, it would be much better to have py_elog available on PyPI. 

If you are not intending to make it, I can fork this, add a workflow to generate a python package and afterward I will file a pull request. 

Let me know,

**Comment by abulgher** [comment]
I'm closing it since @simongregorebner is now maintainer of the py_elog package on pypi.

**Comment by simongregorebner** [comment]
@abulgher thanks a lot for closing! I forgot about it yesterday
