### ISSUE TITLE
Problem while deleting a message

### ISSUE THREAD

**Issue by matteopanca** [paulscherrerinstitute/py_elog#4]
Hi,
I'm working with Python 3.5.3 on Windows 10.
I tried to delete a message on a localhost elog. It seems to me that the method "delete" checks the existence of the message after having deleted it. In my elog, I had just one message (with id=1). The command

> logbook.delete(1)

correctly deleted the message, but it also returned the following error:

> LogbookInvalidMessageID                   Traceback (most recent call last)
> ipython-input-45-75f4b23545cf in module()
> ----> 1 logbook.delete(1)
> 
> c:\anaconda3\lib\site-packages\elog-1.1.0-py3.5.egg\elog\logbook.py in delete(self, msg_id)
>     288                                     allow_redirects=False, verify=False)
>     289
> --> 290             self._check_if_message_on_server(msg_id) # check if something to delete
>     291             self._validate_response(response) # raises exception if any other error identified
>     292
> 
> c:\anaconda3\lib\site-packages\elog-1.1.0-py3.5.egg\elog\logbook.py in _check_if_message_on_server(self, msg_id)
>     357             # the html code.
>     358             if re.findall('<td.*?class="errormsg".*?>.*?</td>', resp_message.decode('utf-8'), flags=re.DOTALL):
> --> 359                 raise LogbookInvalidMessageID('Message with ID: ' + str(msg_id) + ' does not exist on logbook.')
>     360
>     361         except requests.RequestException as e:
> 
> LogbookInvalidMessageID: Message with ID: 1 does not exist on logbook.

Do you have any hint?

Many thanks,
Matteo

**Comment by simongregorebner** [comment]
Very embarrassing bug lurking around - should have been detected with a test - thanks for reporting
