### ISSUE TITLE
Bug in the *new* attachment handling

### ISSUE THREAD

**Issue by abulgher** [paulscherrerinstitute/py_elog#41]
I have found a bug in the new way (I have implemented :-( sigh!) attachment are managed. 

When comparing a new attachment file to an existing one, the first check is done on the filename.

ELOG is replacing all spaces with _ internally. So if you upload a new attachment with spaces in the filename, this will never match any existing attachment simply because spaces are removed.

In order not to limit the freedom of the user, the filename of the new attachments is manipulated internally to replace spaces with _.

I have submitted a PR #40 to fix this misbehaviour.

**Comment by simongregorebner** [comment]
Thanks for the fix and taking care of this!

**Comment by abulgher** [comment]
My pleasure :)
