### ISSUE TITLE
.decode('utf-8') throws an error if not utf-8; suggest to add `'ignore'` ?

### ISSUE THREAD

**Issue by iljabek** [paulscherrerinstitute/py_elog#5]
```
  File ".../elog-1.3.0-py3.5.egg/elog/logbook.py", line 242, in read
  File ".../elog-1.3.0-py3.5.egg/elog/logbook.py", line 361, in _check_if_message_on_server
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 4129: invalid start byte
```

should `.decode('utf-8')` be exchanged with `.decode('utf-8','ignore')` ?
or some optional toggle?

* https://docs.python.org/3/howto/unicode.html#the-string-type
* https://github.com/paulscherrerinstitute/py_elog/blob/b75a715166d6cffbb6190e8cb9087b31c4a25f73/elog/logbook.py#L258
* https://github.com/paulscherrerinstitute/py_elog/blob/b75a715166d6cffbb6190e8cb9087b31c4a25f73/elog/logbook.py#L361
* https://github.com/paulscherrerinstitute/py_elog/blob/b75a715166d6cffbb6190e8cb9087b31c4a25f73/elog/logbook.py#L468

**Comment by simongregorebner** [comment]
could you please file a pull request regarding this?
