### ISSUE TITLE
Downgrading to Python 3.5

### ISSUE THREAD

**Issue by matteopanca** [paulscherrerinstitute/py_elog#8]
Hi,
I was trying to install py_elog with `conda install -c paulscherrerinstitute elog`, but I have been asked to downgrade from Pytohn 3.6.5 to 3.5.6.
![image](https://user-images.githubusercontent.com/20088214/58946570-79c79080-8786-11e9-85dd-62b1849915a9.png)
Is it normal or I should be able to use py_elog also with 3.6?
Thanks!

**Comment by simongregorebner** [comment]
the conda package right now has a 3.5 python dependency for some reasons, but it will work on any version >3.5

**Comment by simongregorebner** [comment]
I just build and uploaded a 3.6 version
